name: run

on:
  push:
    branches: [ scripts ]
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  build:
    strategy:
      matrix:
        branch: [ver/1.16, master]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Run ${{ matrix.branch }}
      env:
        GIT_ID_RSA: ${{ secrets.GIT_ID_RSA }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H -t rsa github.com > ~/.ssh/known_hosts
        echo "$GIT_ID_RSA" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global user.email tsao-chi@the-lingo.org
        git config --global user.name 'ㄗㄠˋ ㄑㄧˊ'
        git clone -b ${{ matrix.branch }} https://github.com/Spottedleaf/Tuinity.git ~/Tuinity
        cd ~/Tuinity
        ./tuinity patch
        ./tuinity upstream up
        ./tuinity patch
        ./tuinity rebuild
        git add .
        ./scripts/upstreamCommit.sh
        git push --force git@github.com:tsao-chi/Tuinity-autoupstreamupdate.git
